name: Deploy server
on:
  push:
    branches:
      - dev
    paths:
      - packages/obsidian-live-share-server/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Move server files
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./packages/obsidian-live-share-server/
          remote_path: /srv/server
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
      - name: Restart docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/server
            docker-compose down
            docker-compose up -d --build
