name: deploy
on:
  push:
    branches:
      - dev
    workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      # - name: Install packages
      #   run: |
      #     npm install -g lerna
      #     lerna bootstrap
      # - name: Create production file
      #   run: npm run build
      #   working-directory: "packages/obsidian-live-share"
      # - name: Move server files
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete --include="packages/obsidian-live-share-server" --exclude='packages/obsidian-live-share-server/node_modules'
      #     remote_path: /srv
      #     remote_host: ${{ secrets.SSH_HOST }}
      #     remote_user: ${{ secrets.SSH_USERNAME }}
      #     remote_key: ${{ secrets.SSH_KEY }}
      # - name: Move plugin files
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete --include="packages/obsidian-live-share/main.js" --include="packages/obsidian-live-share/styles.css" --include="packages/obsidian-live-share/manifest.json" --include="packages/obsidian-live-share/data.json" --exclude='packages/obsidian-live-share/node_modules'
      #     remote_path: /srv/obsidian-live-share/
      #     remote_host: ${{ secrets.SSH_HOST }}
      #     remote_user: ${{ secrets.SSH_USERNAME }}
      #     remote_key: ${{ secrets.SSH_KEY }}
      - name: Restart server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/obsidian-live-share-server && ./run.sh
