name: deploy
on:
  push:
    branches:
    - dev
    workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: dev
    - name: Create production file
      run: npm run dev
      working-directory: "./packages/obsidian-live-share"
    - name: Move files
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        remote_path: /srv
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_pass: ${{ secrets.SSH_PASSWORD }}
    - name: Restart server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            cd /srv/obsidian-live-share/packages/obsidian-live-share-server && ./run.sh