name: Deploy plugin
on:
  push:
    branches:
      - dev
    paths:
      - plugin/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Install packages
        run: npm install
        working-directory: "plugin"
      - name: Create production file
        run: npm run build
        working-directory: "plugin"
      - name: Move plugin files
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --include="main.js" --include="styles.css" --include="manifest.json" --exclude="*"
          path: ./plugin
          remote_path: /home/trey/vault/.obsidian/plugins/obsidian-live-share
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
