name: deploy
on:
  push:
    branches:
      - dev
    workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
      # - name: Install packages
      #   run: npm install
      #   working-directory: "packages/obsidian-live-share"
      # - name: Create production file
      #   run: npm run build
      #   working-directory: "packages/obsidian-live-share"
      - name: Move server files
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude="*"
          remote_path: /srv/server
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
      - name: Move plugin files
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude="*" --include="./packages/obsidian-live-share/main.js" --include="./packages/obsidian-live-share/styles.css" --include="./packages/obsidian-live-share/manifest.json" --include="./packages/obsidian-live-share/data.json"
          remote_path: /srv/plugin
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
      - name: Install node_modules and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/server
            npm install
            ./run.sh
